### ISSUE TITLE
I want to add my project to the list

### ISSUE THREAD

**Issue by VirreV** [nti-stockholm/awesome-nti-stockholm#1]
Please fill in your details under following titles

**The name of the project**
RoomSeeker

**Describe the project in a maximum of three sentences**
A software to make navigation simpler in school.

**Link to the project on GitHub**
https://github.com/VirreV/RoomSeeker

**Is it a *gymansiearbete* or _other project_**
This is a gymnasiearbete

**Comment by alvarlagerlof** [comment]
Your project is now added
