### ISSUE TITLE
I want to add my project to the list

### ISSUE THREAD

**Issue by olvrb** [nti-stockholm/awesome-nti-stockholm#2]
Please fill in your details under following titles

**The name of the project**
nti-lan

**Describe the project in a maximum of three sentences**
A booking service for NTI lan parties

**Link to the project on GitHub**
https://github.com/olvrb/nti-lan

**Is it a *gymansiearbete* or _other project_**
free time project

**Comment by alvarlagerlof** [comment]
I've added your project
